title: Pauls Storyline
description: "A few things"
author:
  name: "Paul Kukiel"
  email: "kukielp@gmail.com"
  url: "https://kukiel.dev"

baseurl: /
rssUrl: "https://kukiel.dev"

source: .
destination: ./_site
permalink: /posts/:title
paginate: 5
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Paul Kukiel"
year : "2020"

google_analytics: UA-166895844-1